services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fleet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports: 
      - "5050:80" 
    depends_on:
      - postgres

volumes:
  postgres_data:
